#!/usr/bin/env python
# coding: utf-8

# Image To Pencil Sketch With Python

# Importing necessary modules for converting into pencil sketch

# In[10]:


get_ipython().system('pip install cv2module')


# Module cv2

# In[3]:


import cv2


# Importing a Lamborghini Image

# In[11]:



image = cv2.imread("C:/Users/Vignesh Raju/Desktop/th.jpg")
cv2.imshow("Lamborghini", image)
cv2.waitKey(0)


# Now the next step is to change the new grayscale image

# In[12]:


gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2.imshow("Change", gray_image)
cv2.waitKey(0)


# Now the next step is to invert the new grayscale image:

# In[13]:


inverted_image = 255 - gray_image
cv2.imshow("Inverted", inverted_image)
cv2.waitKey()


# Now the next step in the process is to blur the image by using the Gaussian Function in OpenCV

# In[7]:


blurred = cv2.GaussianBlur(inverted_image, (21, 21), 0)


# Then the final step is to invert the blurred image, then we can easily convert the image into a pencil sketch

# In[14]:


inverted_blurred = 255 - blurred
pencil_sketch = cv2.divide(gray_image, inverted_blurred, scale=256.0)
cv2.imshow("Sketch", pencil_sketch)
cv2.waitKey(0)


# And finally, if you want to have a look at both the original image and the pencil sketch then you can use the following commands

# In[15]:


cv2.imshow("original image", image)
cv2.imshow("pencil sketch", pencil_sketch)
cv2.waitKey(0)


# In[ ]:




